# Generated by Django 6.0.6 on 2026-07-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_pincode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
